version: "3.7"
services:
  web:
    image: nginx:alpine
    container_name: server_laravel
    environment:
      - "DB_PASSWORD=123"
      - "DB_HOST=db"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
    volumes:
      - ./web/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php 
      - db 
    networks:
      - laravel-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./web/:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel-network

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: developer
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_PASSWORD: 123
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - laravel-network

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./web:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php 
    networks:
      - laravel-network
  
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db 
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    ports:
      - "8000:8000"
    networks:
      - laravel-network

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./web:/var/www/html
    working_dir: /var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
    entrypoint: ["npm"]
    networks:
      - laravel-network

# Docker Networks
networks:
  laravel-network:
    driver: bridge
